env:
  browser: true
  es2021: true
extends: 
  - eslint:recommended
  - plugin:astro/recommended
  - plugin:jsx-a11y/recommended
  - prettier
  - plugin:prettier/recommended
plugins: 
  - jsx-a11y
  - prettier
  - astro
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: ["*.astro"]
    parser: astro-eslint-parser
rules:
  prettier/prettier:
    - error
  eqeqeq:
    - error
    - always
  no-constant-condition:
    - off
  prefer-const:
    - error
  no-fallthrough:
    - off
  no-async-promise-executor:
    - off
