env:
  browser: true
  es2021: true
extends: 
  eslint:recommended
  plugin:astro/recommended
  plugin:jsx-a11y/recommended
plugins: 
  - jsx-a11y
  - astro
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  files: ["*.astro"]
  parser: astro-eslint-parser
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
